### PR TITLE
Add Harbor review

### PR DESCRIPTION
**Pull request by resouer**
Harbor Graduation Recommendation is added.

**Note**: the review conclusion is Harbor is ready for the CNCF Graduation stage without further concerns.

### CODE REVIEW

**Comment by michmike** [comment]
thank you @resouer for the review! we appreciate it!

**Comment by resouer** [comment]
@amye Seems I still can't merge PRs in SIG App Delivery repo :-/

**Comment by caniszczyk** [comment]
@resouer you never accepted the invite :)? https://github.com/cncf/sig-app-delivery/invitations

**Comment by resouer** [comment]
@caniszczyk I see ... that should be the problem. Now "This invitation has expired", any chance to send it again? I will watch my inbox.

**Comment by amye** [comment]
Done

**Pull request merged**
