### PR TITLE
chore(Updated diagrams): operator white paper

### PR DESCRIPTION
**Pull request by AlexsJones**

### CODE REVIEW

**Review by OmerKahani — APPROVED** [review]
Thanks

**Comment by thschue** [comment]
@jlk: What do you think about the redrawing operator-wg/whitepaper-community-review/img/04_1_operator_model.png? Does this still correspond to what you wanted to express here?

**Review by thschue — CHANGES_REQUESTED** [review]
Currently, it's a bit unclear for me if the security drawing still reflects the authors meaning. After this is clarified, it's perfectly fine for me to merge it. Thank you for your efforts unifying and redrawing them all ...

**Comment by jlk** [comment]
Guys - sorry for the delay. Was trying to contact the original artist of that diagram but he's quiet - maybe on vacation or something. The diagram looks fine although a few words in the lower left of the original I can't quite grok.

That said, I think the only change I'd suggest @AlexsJones would be to make the line between `K8s Control Plane` circle and `Operator` circle have an arrow on both ends. Thanks for cleaning these up. :)

**Comment by AlexsJones** [comment]
Thanks for the clarification @jlk this is done.

**Review by thschue — APPROVED** [review]
lgtm

**Pull request merged**
