### PR TITLE
Mention Kopf for Kubernetes operator frameworks (2nd try)

### PR DESCRIPTION
**Pull request by nolar**
Issue: #40. Replaces #58. Based on the #63 guidelines.

### CODE REVIEW

**Comment by nolar** [comment]
Though, I'm not sure what is "a couple of paragraphs" is: is 2 paragraphs and one code snippet considered "a couple"?

**Review by thschue — APPROVED** [review]
lgtm

**Comment by OmerKahani** [comment]
> Though, I'm not sure what is "a couple of paragraphs": are 2 paragraphs and one code snippet considered "a couple"? Or is it covered by the "how does it work in a nutshell" question?

Looks good, thanks for being the first!

**Review by OmerKahani — APPROVED** [review]

**Comment by nolar** [comment]
Hi. Do you need something from me before merging it?

**Review by thschue — APPROVED** [review]

**Comment by nolar** [comment]
Thanks!

**Pull request merged**
