### PR TITLE
Mention Kopf for Kubernetes operator frameworks

### PR DESCRIPTION
**Pull request by nolar**
I'm not sure what is the supposed format here and would appreciate some guidance: is it a table (just not formatted)? Or is it a list? How long a description should be? Should every framework have its own page, as the Framework_1 & Framework_2 links hint? What are possible statuses of the frameworks besides "Not even created"?

Issue: #40

### CODE REVIEW

**Comment by OmerKahani** [comment]
@nolar those are great questions. We will discuss them in the next WG meeting (Wednesday 10th)

**Comment by Jenniferstrej** [comment]
@nolar  - we had a chat about this in our meeting today and I have a PR with clearer guidelines https://github.com/cncf/sig-app-delivery/pull/63/files

Please feel free to create an issue "**Operator Framework for Kubernetes - Kopf**" -  I will then make sure it's added to the project board/in progress. (at the moment I can't get anyone in the assignee tab it seems. I am trying to verify how I can get that).

There is a "**Contributors**" section on the White Paper, and you should add your name there when making a PR. Even if Github admin stops us from certain things we will absolutely make sure you are given the deserved credit.

Please let me know if you have any questions! And thanks for contributing :)

**Comment by Jenniferstrej** [comment]
@nolar - If you are ok with the above, I'm going to close this PR in favor of the revised formatting.

**Comment by nolar** [comment]
Closing in favour of #66.

@Jenniferstrej I'm sorry, I didn't get it about an issue. Why an issue? Isn't a PR better (can be merged without effort)?

**Comment by Jenniferstrej** [comment]
@nolar - we are tracking the project with issues (on the TODO list so people know what tasks no one has picked up yet), but a PR, if associated with the Project, is also fine so go for it 👍 Thanks!

**Comment by nolar** [comment]
@Jenniferstrej I see. I cannot assign projects to PRs (or change any fields on the right column), so I've created #67.

**Pull request closed without merging**
