### PR TITLE
Add updates to Operator Security Scope and Vulnerability Analysis

### PR DESCRIPTION
**Pull request by cseader**
merging new updates to a few sections in security and adding Cameron Seader as Contributor.

### CODE REVIEW

**Comment by thschue** [comment]
We merged the chapter docs to one "large" document for the review -> https://github.com/cncf/sig-app-delivery/tree/review-draft-1/operator-wg/whitepaper-community-review. Please add your changes to this document.

**Review by thschue — CHANGES_REQUESTED** [review]
We merged the chapter docs to one "large" document for the review -> https://github.com/cncf/sig-app-delivery/tree/review-draft-1/operator-wg/whitepaper-community-review. Please add your changes to this document.

**Comment by cseader** [comment]
OK. I will move this. Thanks
Cameron

**Review by thschue — APPROVED** [review]
lgtm

**Pull request merged**
